# Generated by Django 2.2.1 on 2019-05-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rate_1',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rate_2',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rate_3',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rate_4',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rate_5',
        ),
    ]
